name: stable-spearhead

on:
  workflow_dispatch:
    inputs:
      new_release:
        type: boolean
        description: Force new Release
      force_dispatch:
        type: boolean
        description: Force dispatch
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]
    env:
      APP_NAME: VSCodium
      ASSETS_REPOSITORY: ${{ github.repository }}
      VERSIONS_REPOSITORY: ${{ github.repository_owner }}/versions
      OS_NAME: osx
      VSCODE_ARCH: arm64
      VSCODE_LATEST: yes
      VSCODE_QUALITY: stable

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clone VSCode repo
        run: . get_repo.sh

      - name: Check existing VSCodium tags/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_RELEASE: ${{ github.event.inputs.new_release }}
        run: . check_tags.sh

      - name: Compute cache key
        id: yarnCacheKey
        run: echo "value=$(node build/azure-pipelines/computeYarnCacheKey.js)" >> $GITHUB_OUTPUT
        if: env.SHOULD_BUILD == 'yes'

      - name: Get yarn cache directory path
        id: yarnCacheDirPath
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        if: env.SHOULD_BUILD == 'yes'

      - name: Cache yarn directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarnCacheDirPath.outputs.dir }}
          key: ${{ env.OS_NAME }}-${{ env.VSCODE_ARCH }}-yarnCacheDir-${{ steps.yarnCacheKey.outputs.value }}
          restore-keys: ${{ env.OS_NAME }}-${{ env.VSCODE_ARCH }}-yarnCacheDir-
        if: env.SHOULD_BUILD == 'yes'

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Update <quality>.json
        run: ./update_qualityjson.sh
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        if: env.SHOULD_BUILD == 'yes'

      - name: Prepare source
        run: ./prepare_src.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Release source
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: ./release.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Dispatch builds
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: 'stable'
        if: env.SHOULD_BUILD == 'yes' || github.event.inputs.force_dispatch == 'true'
