name: stable-spearhead

on:
  workflow_dispatch:
    inputs:
      new_release:
        type: boolean
        description: Force new Release
      force_dispatch:
        type: boolean
        description: Force dispatch
      dont_update:
        type: boolean
        description: Don't update VSCode
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: macos-14
    env:
      APP_NAME: VSCodium
      ASSETS_REPOSITORY: ${{ github.repository }}
      VERSIONS_REPOSITORY: ${{ github.repository_owner }}/versions
      OS_NAME: osx
      VSCODE_ARCH: arm64
      VSCODE_LATEST: ${{ github.event.inputs.dont_update == 'true' && 'no' || 'yes' }}
      VSCODE_QUALITY: stable

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clone VSCode repo
        run: . get_repo.sh

      - name: Check existing VSCodium tags/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_RELEASE: ${{ github.event.inputs.new_release }}
          IS_SPEARHEAD: 'yes'
        run: . check_tags.sh

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./build.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Update <quality>.json
        run: ./update_qualityjson.sh
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        if: env.SHOULD_BUILD == 'yes' && github.event.inputs.dont_update != 'true'

      - name: Prepare source
        run: ./prepare_src.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Release source
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: ./release.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Dispatch builds
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: 'stable'
        if: env.SHOULD_BUILD == 'yes' || github.event.inputs.force_dispatch == 'true'
